apiVersion: v1
kind: Secret
metadata:
    name: ghcr-image-updater
    namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:UFlQd9E5n+Np0bfOQQ1cIe0hgXaYXkg8oE1opYhOhIHV6O1VW+XbEm70fcVXs1z7so3kwAdvoFPams3vWctp5esspSiyOPvgU71fxTn8yBW6OqID4MktYrv1Kt2jCJpxnUxjyMbaK3232KNK1zl2FSodyAjdlvT5vmNDuAw2Qe+p0xZJ8o9QFP1ZFAxvrnltp6KK8uJeUky2yaKNY7nUuj2TubMeqBbC42D7hw==,iv:3abtOTLp6mJzW4KEbi55/rhXDcDykZdqunRaVwLCf1c=,tag:IoZGKFjl8qa1sRLw8XVYoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBha2JtM3FGTTEzRnBuSG5Z
            U2ZldHR0N2c4UUxpR2NIVGNpSVBrZ0dOV1RjCnQ1Q0NpMkVHK1RnT0hPY3V2M1Vk
            SFJQR0dJeXJ0eGxmUUR1azhpM3dQQm8KLS0tIFQrYytCQjNZSEVHTVpSMTJ0T1Bu
            aVRENkJEaXUwTUhhNkZmbW5LWFlaMzQKy17j4ku36GGDQYoB5J/c1tUqZuJBTxAh
            pVBExukprAR6I8xzDPclLQRi/qgZL9z1PVh4kWoSRao9BalLzPUACg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6ljghzq69qywmsx9j55d3q8ydnxgw34y3vkrs646cjm5357e48q25uqdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T17:37:21Z"
    mac: ENC[AES256_GCM,data:75HKdVCkT32Cw82ye2wf2hLHpqfk1C0mQbzdue/iy6pYtN0hu+H/ci6sOWZwXc8Q0yL+jFmHkcEdyRBdQZwLTSDhZRWD+TaYrc1XKC+JEgvLbDx7m+6I9UCHe1MRcLTZw16eCdSm0l0V1ombH6RIBlCJcnkuzrOJ0FvhYEpntgs=,iv:miVgXmsaEBqbJ/4zJu+aYNS17yxVjU8E0B6SOxBqil8=,tag:HGJsrcjXGo0XlEHd5/S2Nw==,type:str]
    version: 3.13.1
