apiVersion: v1
kind: Secret
metadata:
    name: git-write-token
    namespace: argocd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:nK9A4eWj,iv:VJjGWEwsoTIGHePf7UzhQXYJcn5VCY/rdh64VNjyt+Y=,tag:PmqV6rxBejKvLHor82xuBQ==,type:str]
    password: ENC[AES256_GCM,data:C2JDWAGV8uGM9Fz86F9YBIf125JcYwuegTSf4cQ+ckU/u/rUxkUOog==,iv:DolZysUXjpDHqDVSQRz3v6OU3B7udD9axhdMGpJ5Xaw=,tag:nF688r3H1iIXIjUPPVjv6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa3pLU2IwdWdvRmRJdmRD
            c2M5RFEyMjNEY3dGMnl0TEhXMCsxUXl5T3hjCnB3c0czZHZhN1RudnBsbTNHbXlJ
            cUNBUnQwaFBRd1UzY09GUDZsc0xjbVEKLS0tIGhsWitTYzhuUEd3UmVZTnVBQktu
            QzJVbHVRSyt3NjJEY2xIOEtVSFdUV2cKXWW8SVKhgtJEkeQW0Cjr2FIwUAARt8Jh
            7F6E7TBVjB9dJ9UKEFS9YRl3olqwQ9WRifnWnNsJlvMp2fSP3IHXbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6ljghzq69qywmsx9j55d3q8ydnxgw34y3vkrs646cjm5357e48q25uqdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T17:11:10Z"
    mac: ENC[AES256_GCM,data:o2mxwh9GA63pfT9cuT/U8qv0TwLefiNzTJyTdZODKAUu9xnr/kfT8g2OiyLWHd6Qhtdrts1ZrTYm5MYTdekbtRkGE6g0ggIyrws8U3e8xSHyih9gPNk1hokszUs8mTRdPkpraxQvBkTeoWPzk/BFNeQgivC+j4+wPYzilSKF1UI=,iv:BjIHazz8ZDoDAvdQoILwo9XzCAJTGCOWgCyYITLMmuY=,tag:Sd/WExcN7OZt3sIg4HzqPQ==,type:str]
    version: 3.13.1
