apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-service
  namespace: argocd
spec:
  project: platform

  source:
    repoURL: https://github.com/eann1s/cicd-platform.git
    targetRevision: feature/gitops-argocd
    path: gitops/apps/node-service
  
  destination:
    server: https://kubernetes.default.svc
    namespace: node-service
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
