name: Build candidate
description: Build candidate
inputs:
  images: {required: true, description: "Images to build"}
  context: {required: true, description: "Context path"}
  dockerfile_path: {required: true, description: "Dockerfile path"}
  publish: {required: false, description: "Publish image"}
  tags: {required: false, description: "Image tags"}
runs:
  using: composite
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

    - name: Generate metadata
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
      with:
        images: ${{ inputs.images }}
        tags: |
          type=sha
          type=ref,event=branch
    
    - name: Build and optionally push
      id: build-image
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile_path }}
        push: ${{ inputs.publish == 'true' }}
        tags: ${{ inputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
outputs:
  digest:
    value: ${{ steps.build-image.outputs.digest }}
    description: "Digest of the built image"
