apiVersion: v1
kind: Secret
metadata:
    name: alert-manager-telegram-bot-token
    namespace: monitoring
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:HK+uAqoFU+CJNLWUHD0hSLTWWD4nlSMl+V/5of2w8n2p6fMlzmmAZb6B/KO4Vw==,iv:z4AEftJCfcY4ZZ2B+93NuOEy2Y0mHSmVDT0kvn9Arws=,tag:327IlVGzQWHeSDpM96FKrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNlNiVnhmRWliWVVrUXBF
            K0l1ZHRqYzJaZjk5Tm95VVhrUEdVajhwNTAwCkNkUFFhMWdJL3YvcmZTWEtQcmh3
            TDdoaXNJaDJueENoSGtORzBoS1p3elkKLS0tIGVlcFArN2Q3WnEzRnlhelFyT3ZG
            WmNXbXMyWDRla1FRc0hNQ1VtSHFvejAKB+ma98LK5/Df6A0Nii4SvQIhvQ7kQMlg
            x6poEFql1sAQPvLW7zwNuz2x9uyBSFNb77PfQuHyW4DVeBq6r6K1CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6ljghzq69qywmsx9j55d3q8ydnxgw34y3vkrs646cjm5357e48q25uqdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T18:04:49Z"
    mac: ENC[AES256_GCM,data:jO5rxiYWSQtcPEzyuzj22vlbFEtqqeCOF5+nc9WElZk5c4QJFQMr4N/nDI2rb0gXJeVMxV+3aaGpjRxyTUAHxGeCs/vBEd0QADKvtvy+4OKrcABTLOlwlUzbE5Y1DqN5ty6ANWpUey2it93bJM5z1UlK6STkOr9aYIPhK2YeOHY=,iv:doMtj4uwM77bJT1eErmZjaSFoNA98Mob2mCE/o31YTA=,tag:doK19Ikv4EmcDhw/cnSX7g==,type:str]
    version: 3.13.1
