apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: node-service
resources:
  - service.yml
  - deployment.yml
  - namespace.yml

images:
  - name: node-service
    newName: ghcr.io/eann1s/cicd-platform/node-service
    digest: sha256:d4b8d0eada0490b36e90117cfa178fae53ba361315cd378a893beeb6306bd2ff
