apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: node-service
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:tDusRBvE4XqbDWOgYW2yk7VyQcrQCDSjyc2NLJgh039755e3jHYal4Iv+00KihIPirBQdNiuLL/HLOwsjT945ZeOhGawYl/Dfa/UmAgNx5jY0e7n8l8VGiNV3MpBJEeOPyTm87w+5BWngfzRpwOSO5+l4NnODqm6AiDsr14b00ubUteGbA0/yI0cbU3WsBTbBwjoGTkWOEwNvUpIU/kotsJFnhfg134xurUzrg==,iv:tLjkFfCv0R7RVlmfp1iNCML2OqzRQrJChGpUS9Zkf8o=,tag:vjakSD5N2zQRUJNIB5QFXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RnhjS2V3WDB0SUw4S3JV
            QjBpaXFCL3JMZGtKU2MyVnBkdEJZbHhQVERRClpXN3pib0o0N3d1dVB1M3pXK1FP
            Rko2OGEvV0UyZ1NlVHJjQkZ4ZWJqeUkKLS0tIFoxYkZJWlJNWVl4Z1FKOHcrVEtu
            M3RhYURZSnZic3M0K3dISWhlaWREM28KL01NZncakcIRdVcqJc2cBRqxzK+GdVde
            0Qxd8uSuWFimGXJTJPfCV189svH6tWaIQjefRgQsyIEEqZ4X1gBAnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6ljghzq69qywmsx9j55d3q8ydnxgw34y3vkrs646cjm5357e48q25uqdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T17:34:43Z"
    mac: ENC[AES256_GCM,data:JAoO9cnU9i8JDCYgXnokk50EDLlvIKlblf0qpo1V1hvqNa258AQRyv7s/AG7gdfcvYt1MB6NyXYls36n7e6ltW9UPhs6QS5rWV8L9nBAxuurG/PvjAiXnJcQhMsNdx4Gj98JyYg0kB8jsyfXdTDPfKd+Ioljt9YsnTtM59coZls=,iv:7U4zBqTgCaNBOz1ariiRmxG5uzcjBpAomSFYO1zGwvs=,tag:o4TXfpfvyRApOYjs5JEwNg==,type:str]
    version: 3.13.1
