name: Image promote
description: Promote image
inputs:
  image: {required: true, description: "Image to promote"}
  image_digest: {required: true, description: "Digest of the image to promote"}
runs:
  using: composite
  steps:
    - name: "Publish"
      shell: bash
      run: |
        docker buildx imagetools create \
          --tag ${{ inputs.image }}:latest \
          --tag ${{ inputs.image }}:${{ github.sha }} \
          ${{ inputs.image }}@${{ inputs.image_digest }}