name: Security Post Scan
description: Image vulnerabilities scan + SBOM generation
inputs:
  image_with_digest: {required: true, description: "Image with digest"}
  severity: {required: true, description: "Severity of vulnerabilities to scan for. E.g. HIGH,CRITICAL"}
runs:
  using: composite
  steps:
      - name: Image vulnerabilities scan
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          scan-type: image
          scan-ref: ${{ inputs.image_with_digest }}
          severity: ${{ inputs.severity }}
          ignore-unfixed: false
          exit-code: 1
          format: 'json'
          output: 'image-trivy-report.json'
          vuln-type: os,library
      
      - name: SBOM generation
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
        with:
          image: ${{ inputs.image_with_digest }}
          format: cyclonedx-json
          output-file: image-sbom.cdx.json
      
      - name: Upload reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: image-security-artifacts
          if-no-files-found: error
          path: |
            image-trivy-report.json
            image-sbom.cdx.json

