apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: go-service
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:TWCV9ABUkx674vhduCZWF+6B+6KH9Y8+7SzIhuZeJtnXr4amzubsGNj3LOxXVmQZ5LdzUHQcjxZwmW209AoFEoGraKkpv9nRXREQx74fBQvjzsye9DNCbP8MoV2brpnjGg+9HV0NPDorxGFOGdWGv9xUv+nIRXHDPblKqOeCn4i1/jS0SBnYJbUCG49rgoPWCTiwfvdl3H4CiqKUJsQJy2M2GLJu75wIIRrYgg==,iv:VirhB683eGEh+mlsoPaJJyRfchmKT4QSxBGlRe7O/cs=,tag:d0AN/zncw0aM/9IUEJrq8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN2hhZ2gwcUtFMEtDeFlY
            NFRnczFBQ1JvUDk3WVMyR3BlS3REQnFndVFrCll6eDg3aEZXdmttbE15dTZiY2Rh
            QktKSGNRV1ZPdkdEYWZqd0ZnVmF3Qm8KLS0tIFBiMGY0eUNrejZWS3BRaGRCSm1X
            dVZsd1RhZEJSRlVJMlM2UXc2T0NQSWsKE8Kl5i/5eWwp1KzSVvRCF7ux0hr0G05p
            x0GYL/kgU1jIwC4e6NRkL4lkzCoBjTUZwFdbP1W5BgyvDaXV9b9HFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p6ljghzq69qywmsx9j55d3q8ydnxgw34y3vkrs646cjm5357e48q25uqdv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T17:31:36Z"
    mac: ENC[AES256_GCM,data:AcyoW0fmz6pHK6CE1FDStcdx3ZbP0Zp0ST6/CfqO3EA8TWlJETxM7XLM4fVsNsKbH/OvWwK0MTJhqxs7R0OctBjRxPSDhR1THHY6nV+h7z61ighwsGmPM6gtoAolTkk7fOVs+2Prhd8T+sUtwvr09sNaVOFa9t1/xtWFWFwT354=,iv:dOBfUskcaf8FhQGvZHTzCcipFzfnGtJULe0Wu9+e3mI=,tag:xviLP9v1QbEaJHnWpweANQ==,type:str]
    version: 3.13.1
