name: ci-ts-service

on:
  pull_request:
    paths: ["consumers/node-service/**", ".github/workflows/ci-ts-service.yml", ".github/workflows/reusable/reusable-ts-ci.yml", ".github/workflows/reusable/reusable-release.yml", ".github/actions/**"]
  push:
    branches: ["master"]
    paths: [ "consumers/node-service/**", ".github/workflows/ci-ts-service.yml", ".github/workflows/reusable/reusable-ts-ci.yml", ".github/workflows/reusable/reusable-release.yml", ".github/actions/**"]

jobs:
  call_pr:
    if: github.event_name == 'pull_request'
    permissions: {contents: read}
    uses: "./.github/workflows/reusable/reusable-ts-ci.yml"
    with:
      service_path: consumers/node-service
      image_name: node-service
  
  ci_push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions: {contents: read}
    uses: "./.github/workflows/reusable/reusable-ts-ci.yml"
    with:
      service_path: consumers/node-service
      image_name: node-service
  
  release_push:
    needs: [ci_push]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions: {contents: read, packages: write, id-token: write}
    uses: "./.github/workflows/reusable/reusable-release.yml"
    with:
      service_path: consumers/node-service
      image_name: node-service

